### ISSUE TITLE
Bugs in XQuery syntax highlighter

### ISSUE THREAD

**Issue by wcandillon** [arolle/atom-language-xquery#5]
The syntax highlighter is extremely buggy and I have addressed the issues in this package: https://github.com/wcandillon/language-jsoniq

Would it be worth it to deprecate this package in favor of language-jsoniq? Alternatively this package could copy the xquery.cson file from us.

**Comment by arolle** [comment]
We can definately deprecate this package in favour of language-jsoniq, also as this package uses an [deprecated API](http://blog.atom.io/2015/05/01/removing-deprecated-apis.html). What way would you be best for your project?
[Unpublish/Transferring Ownership](https://atom.io/docs/v0.207.0/behind-atom-maintaining-your-packages#unpublish-your-package)

**Comment by wcandillon** [comment]
Unpublish the package and link to the language-jsoniq repository from the readme of this project? Or whatever works best for you.

**Comment by arolle** [comment]
package is now unpublished on atom.io.
